name: CI
on: [push, pull_request]
jobs:
  Android:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: flutter_app
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v2
        with:
          distribution: "zulu"
          java-version: "11"
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.0.0"
      - run: flutter pub get
      - run: flutter test
      - run: flutter build apk
      - run: flutter build appbundle
  Apple:
    runs-on: macos-latest
    defaults:
      run:
        working-directory: flutter_app
    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.0.0"
          architecture: x64
      - run: flutter pub get
      - run: flutter test
      - run: flutter build ios --release --no-codesign
