name: DjangoCI
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: backend
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.9
        uses: actions/setup-python@v3
        with:
          python-version: "3.9"
      - name: Install pipenv and dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pipenv
          pipenv install --dev
          pipenv check
      - name: Run linter / formatter
        run: pipenv run pre-commit run --files ./*
      - name: Run Django check
        run: pipenv run python manage.py check
      - name: Run Django tests
        run: pipenv run python manage.py test
      - name: Run migrations
        run: pipenv run python manage.py migrate
